"""added solution_votes

Revision ID: 95e948e22322
Revises: 24a11c90580e
Create Date: 2023-11-04 14:03:11.111261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e948e22322'
down_revision: Union[str, None] = '24a11c90580e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('stars_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('stars_count <= 5', name='check_max_stars_count'),
    sa.CheckConstraint('stars_count >= 0', name='check_min_stars_count'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solution_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stars_count', sa.Integer(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('stars_count <= 5', name='check_max_stars_count'),
    sa.CheckConstraint('stars_count >= 0', name='check_min_stars_count'),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('votes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stars_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('stars_count <= 5', name='check_max_stars_count'),
    sa.CheckConstraint('stars_count >= 0', name='check_min_stars_count'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='votes_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='votes_pkey')
    )
    op.drop_table('solution_votes')
    op.drop_table('task_votes')
    # ### end Alembic commands ###
